export const GENDER_MAN = 'LAKI-LAKI'
export const GENDER_WOMAN = 'PEREMPUAN'
export const GENDERS = [GENDER_MAN, GENDER_WOMAN] as const

export const USER_STATUS_NEW = 'NEW'
export const USER_STATUS_PENDING = 'PENDING'
export const USER_STATUS_ACTIVATED = 'ACTIVATED'
export const USER_STATUESESS = [USER_STATUS_NEW, USER_STATUS_PENDING, USER_STATUS_ACTIVATED] as const