export const GENDER_MAN = 'LAKI-LAKI'
export const GENDER_WOMAN = 'PEREMPUAN'
export const GENDERS = [GENDER_MAN, GENDER_WOMAN] as const

export const USER_STATUS_NEW = 'NEW'
export const USER_STATUS_PENDING = 'PENDING'
export const USER_STATUS_ACTIVATED = 'ACTIVATED'
export const USER_STATUESESS = [
	USER_STATUS_NEW,
	USER_STATUS_PENDING,
	USER_STATUS_ACTIVATED,
] as const

export const FILE_TYPE_IDENTITY = 'IDENTITY'
export const FILE_TYPE_MEMBER = 'MEMBER'
export const FILE_TYPE_MODULE = 'MODULE'
export const FILE_TYPE_PROFILE = 'PROFILE'
export const FILE_TYPE_CONSELING = 'CONSELING'
export const FILE_TYPE_ASSETS = 'ASSETS'
export const FILE_TYPE_MEMBER_USER = [
	FILE_TYPE_IDENTITY,
	FILE_TYPE_MEMBER,
	FILE_TYPE_PROFILE,
] as const
export const FILE_TYPES = [
	FILE_TYPE_IDENTITY,
	FILE_TYPE_MEMBER,
	FILE_TYPE_MODULE,
	FILE_TYPE_PROFILE,
	FILE_TYPE_CONSELING,
	FILE_TYPE_ASSETS,
]

export const WHO_CAN_DO_FASILILITATOR = 'FASILITATOR'
export const WHO_CAN_DO_PATIENT = 'PATIENT'
export const WHO_CAN_DO_SELF = 'SELF'
export const WHO_CON_DOES = [
	WHO_CAN_DO_FASILILITATOR,
	WHO_CAN_DO_PATIENT,
	WHO_CAN_DO_SELF
] as const

export const FORM_TYPE_REFLEKSI = 'REFLEKSI'
export const FORM_TYPE_TRAIN = 'TRAIN'
export const FORM_TYPES = [FORM_TYPE_REFLEKSI, FORM_TYPE_TRAIN] as const